### PR TITLE
Build project with Mill

### PR DESCRIPTION
**Pull request by alexarchambault**
This PR:
- switches the build over to Mill
- updates Scala to `2.12.15` / `2.13.8`
- updates scalafmt to `3.5.2`
- makes snailgun not automatically call `isatty` via JNA, in order to make the tests pass on Windows
- uploads snailgun CLI launchers for Linux / macOS / Windows as GitHub release assets, to a release tagged as `nightly` on master, and to the release of a version for actual releases
- assumes the same secrets as [sbt-ci-release](https://github.com/sbt/sbt-ci-release) are set up for publishing to Maven Central

### CODE REVIEW

**Comment by alexarchambault** [comment]
A few useful Mill commands:
- compile everything: `./mill __.compile`
- compile for a specific Scala version: `./mill '__[2.13.8].compile'`
- run tests: `./mill __.test` or `./mill '__[2.13.8].test'`
- generate a native image: `./mill -i 'cli[2.13.8].nativeImage'`, or just `./mill -i nativeImage` (use `show` to get the path, like `./mill -i show nativeImage`)

**Comment by alexarchambault** [comment]
For the master CLI launchers uploads to work, you'll need to create a release for a tag called `nightly`, like [this one](https://github.com/VirtusLab/scala-cli/releases/tag/nightly) for example. The CI will then upload the latest launchers there.

To cut a new release, you'll need to cut the release from the GitHub UI (cutting a *release*, not just a tag). The CI job will later upload launchers there.

**Comment by alexarchambault** [comment]
You'll also need to setup the same secrets as [sbt-ci-release](https://github.com/sbt/sbt-ci-release), for releases to work, and a `GITHUB_TOKEN` secret, so that launchers can be uploaded as GitHub release assets (not sure why, but the default token usually doesn't work for that).

**Review by jvican — APPROVED** [review]
LGTM! Apologies for my delay getting back to you Alex, this looks great :+1:

I'll try setting up the automatic merge process shortly, I'm dealing with something at work right now. In the meanwhile, I can make a manual release if you need it.

**Pull request merged**
